# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agent-browser-skills = {
    pname = "agent-browser-skills";
    version = "5185339ca3fdab9848e11b8ec676eecfdec3733f";
    src = fetchgit {
      url = "https://github.com/vercel-labs/agent-browser";
      rev = "5185339ca3fdab9848e11b8ec676eecfdec3733f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3XDgN/iZvsR54cYIwBeS/3Ls2L+MJShJxvva8EkIBfo=";
    };
    date = "2026-06-10";
  };
  anthropic-skills = {
    pname = "anthropic-skills";
    version = "57546260929473d4e0d1c1bb75297be2fdfa1949";
    src = fetchgit {
      url = "https://github.com/anthropics/skills";
      rev = "57546260929473d4e0d1c1bb75297be2fdfa1949";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1D9otXxDvmKASBu/vtAEWv6kE+U+jG4OxZpRLZbGEF0=";
    };
    date = "2026-06-09";
  };
  chrome-devtools-mcp-skills = {
    pname = "chrome-devtools-mcp-skills";
    version = "228cf3936ad99d9e0c09b43d77fbbac8712f2357";
    src = fetchgit {
      url = "https://github.com/ChromeDevTools/chrome-devtools-mcp";
      rev = "228cf3936ad99d9e0c09b43d77fbbac8712f2357";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-R60LeOR44QywYkOsIXD23Td/FuW2F7edQEw2l8AXiXY=";
    };
    date = "2026-06-11";
  };
  claude-mem = {
    pname = "claude-mem";
    version = "13.5.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/claude-mem/-/claude-mem-13.5.5.tgz";
      sha256 = "sha256-BoKqWLfEWSA0rvf6aPbaNd0fFdkUsHZ3r9vS/H8gAas=";
    };
  };
  context7-skills = {
    pname = "context7-skills";
    version = "e35cb61068fad12cafe011a6487a7a2092f66c1a";
    src = fetchgit {
      url = "https://github.com/upstash/context7";
      rev = "e35cb61068fad12cafe011a6487a7a2092f66c1a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-BCHR3P/tJbAehANWCL+n1j80jOXEFERgRMu0+FoHeb0=";
    };
    date = "2026-06-11";
  };
  dot-skills = {
    pname = "dot-skills";
    version = "a86ba91476c0a3df3c7702f176c53023ea2ffe7c";
    src = fetchgit {
      url = "https://github.com/pproenca/dot-skills";
      rev = "a86ba91476c0a3df3c7702f176c53023ea2ffe7c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Aihfefulnrne5r1wYNwttAy2DtDW3EKcN1e47F7lSw4=";
    };
    date = "2026-05-31";
  };
  humanlayer-skills = {
    pname = "humanlayer-skills";
    version = "ecf602e2f9bb445831e36592af92c36bfad18960";
    src = fetchgit {
      url = "https://github.com/humanlayer/skills";
      rev = "ecf602e2f9bb445831e36592af92c36bfad18960";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xRlJS7kYEtAZ+pCphIVGbOyuRhwuW4JuJG1qDF9ns7o=";
    };
    date = "2026-03-17";
  };
  itechmeat-skills = {
    pname = "itechmeat-skills";
    version = "0ba69fd9bfdecae0dc0b555652cb9d3e3522eec2";
    src = fetchgit {
      url = "https://github.com/itechmeat/llm-code";
      rev = "0ba69fd9bfdecae0dc0b555652cb9d3e3522eec2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AeZxH2PXNOqzN8VLniC0sL6/kAJZrA5u90Uy+2XCEVQ=";
    };
    date = "2026-06-01";
  };
  linear = {
    pname = "linear";
    version = "2.0.0";
    src = fetchurl {
      url = "https://github.com/schpet/linear-cli/releases/download/v2.0.0/linear-aarch64-apple-darwin.tar.xz";
      sha256 = "sha256-Eh/h7ubZCyLnbk6Yy7YkR07s2XCkpMYi/U1QiJtX2sw=";
    };
  };
  linear-cli-skills = {
    pname = "linear-cli-skills";
    version = "fc85b919cdb62a668eecea6ea5484aad9da8f655";
    src = fetchgit {
      url = "https://github.com/schpet/linear-cli";
      rev = "fc85b919cdb62a668eecea6ea5484aad9da8f655";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nmF834DXqLmHDKiAys8FARsXmRWyMKyUF7uDVpq5a8w=";
    };
    date = "2026-05-19";
  };
  oh-my-openagent = {
    pname = "oh-my-openagent";
    version = "4.9.2";
    src = fetchurl {
      url = "https://github.com/code-yeongyu/oh-my-openagent/archive/refs/tags/v4.9.2.tar.gz";
      sha256 = "sha256-Kb1s+mGkMgiI/5qwJZgQ3DZk+ZDZQYWHcGGwpkR4Arg=";
    };
  };
  orca-skills = {
    pname = "orca-skills";
    version = "6762a10f3f819c7da7b84d6942a038d19bb1583f";
    src = fetchgit {
      url = "https://github.com/stablyai/orca";
      rev = "6762a10f3f819c7da7b84d6942a038d19bb1583f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NXx7O01zVv5TAQWe1fJTJZ8ig/AmQALDNI8pV92921I=";
    };
    date = "2026-06-11";
  };
  playwriter-skills = {
    pname = "playwriter-skills";
    version = "9d837c0a8cfb573bc084edbd1d1b7d4e9654c965";
    src = fetchgit {
      url = "https://github.com/remorses/playwriter";
      rev = "9d837c0a8cfb573bc084edbd1d1b7d4e9654c965";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Edro54JOXIRho1be/1gaCBH5e6k1uu+Dia7CJoZL6CY=";
    };
    date = "2026-05-27";
  };
  pup = {
    pname = "pup";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/datadog-labs/pup/releases/download/v1.0.0/pup_1.0.0_Darwin_arm64.tar.gz";
      sha256 = "sha256-f5rIYm+ekn8bHkhsxs2AGqdp5fNte/R4G5j0K3d4uXw=";
    };
  };
  pup-skills = {
    pname = "pup-skills";
    version = "2db49bc167580a0c8d23e16ae0572fec75ef7b8b";
    src = fetchgit {
      url = "https://github.com/datadog-labs/pup";
      rev = "2db49bc167580a0c8d23e16ae0572fec75ef7b8b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-L5Rk5t9rJWGr715X8AwBaj7k4PRFh1Zl60o3qVmyFBE=";
    };
    date = "2026-06-11";
  };
  vercel-skills-cli = {
    pname = "vercel-skills-cli";
    version = "be0dd25b4a8665894a56f45ef582cc02ca802c39";
    src = fetchgit {
      url = "https://github.com/vercel-labs/skills";
      rev = "be0dd25b4a8665894a56f45ef582cc02ca802c39";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-IAbkeN1ZP8z5xTaZafRLMhAlhXBDw+fkfTvjZBoGeqw=";
    };
    date = "2026-06-11";
  };
  wacli = {
    pname = "wacli";
    version = "0.11.1";
    src = fetchurl {
      url = "https://github.com/openclaw/wacli/releases/download/v0.11.1/wacli_0.11.1_darwin_universal.tar.gz";
      sha256 = "sha256-hQDuyJFXNW8Wu4kWD5EwLVE0wGj3ka4t/qUTt2UBa+w=";
    };
  };
  worktrunk-skills = {
    pname = "worktrunk-skills";
    version = "214d82aedabb927c955ee82b1b1fd518588971ff";
    src = fetchgit {
      url = "https://github.com/max-sixty/worktrunk";
      rev = "214d82aedabb927c955ee82b1b1fd518588971ff";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UBvmvqCLzOhq+RwfSIFTgNAN2/03XlOZ4pM140zb/2E=";
    };
    date = "2026-06-11";
  };
  wshobson-agents = {
    pname = "wshobson-agents";
    version = "75ebf8c644f4c5bceb4a60523754a021954cba52";
    src = fetchgit {
      url = "https://github.com/wshobson/agents";
      rev = "75ebf8c644f4c5bceb4a60523754a021954cba52";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lzEcUWtnS3ghi+3kCsJBvwNuVkyIFpQY7qG0UkUUCgA=";
    };
    date = "2026-06-12";
  };
}
