# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agent-browser-skills = {
    pname = "agent-browser-skills";
    version = "b48700c36351aad959d05c5c9bba2fb2fc3f9705";
    src = fetchgit {
      url = "https://github.com/vercel-labs/agent-browser";
      rev = "b48700c36351aad959d05c5c9bba2fb2fc3f9705";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PJVTjPXpyJNhQh+0BrY9o9gPAZTnz8JZmbF9fOlQHxE=";
    };
    date = "2026-07-22";
  };
  agent-slack = {
    pname = "agent-slack";
    version = "0.9.3";
    src = fetchurl {
      url = "https://github.com/stablyai/agent-slack/releases/download/v0.9.3/agent-slack-darwin-arm64";
      sha256 = "sha256-ISvecKk6btX0kRyOc4jLH1a1HuCFABa8K9VbdByiBZY=";
    };
  };
  agent-slack-skills = {
    pname = "agent-slack-skills";
    version = "80f0e8df0299f4f03bce1bed6f8ef3d3da1b65f7";
    src = fetchgit {
      url = "https://github.com/stablyai/agent-slack";
      rev = "80f0e8df0299f4f03bce1bed6f8ef3d3da1b65f7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-l2GQnGHU9OoU0HBsiDu+p9Pv4AMZaN4J0pHqHRSnoH8=";
    };
    date = "2026-07-18";
  };
  anthropic-skills = {
    pname = "anthropic-skills";
    version = "1f630fdf9259cec4a14913127dfd7c3b69ef72eb";
    src = fetchgit {
      url = "https://github.com/anthropics/skills";
      rev = "1f630fdf9259cec4a14913127dfd7c3b69ef72eb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XPXKd05IEiyTPlAPkowfJUal1UfRlxEHo+GgszgHQCI=";
    };
    date = "2026-07-22";
  };
  chrome-devtools-mcp-skills = {
    pname = "chrome-devtools-mcp-skills";
    version = "45262c0a5ca433e4d9d5700e3c1e006ac41f45f5";
    src = fetchgit {
      url = "https://github.com/ChromeDevTools/chrome-devtools-mcp";
      rev = "45262c0a5ca433e4d9d5700e3c1e006ac41f45f5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-WJQHyUDCVKf0J/AjdkBfaHz5xtsl4Fk+T3lLHfoJi6Y=";
    };
    date = "2026-07-22";
  };
  claude-mem = {
    pname = "claude-mem";
    version = "13.12.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/claude-mem/-/claude-mem-13.12.2.tgz";
      sha256 = "sha256-YILjnh1IFt6xJFzMRbvueYjE/hc99JU3wOFmgRW9Tuw=";
    };
  };
  context7-skills = {
    pname = "context7-skills";
    version = "d8885b2308c591bb74a1b8ff586b70d914a11e45";
    src = fetchgit {
      url = "https://github.com/upstash/context7";
      rev = "d8885b2308c591bb74a1b8ff586b70d914a11e45";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-cmSw43HaGiFHA+ts4mF4/76wG/InRgHAXuSn5eZzdTA=";
    };
    date = "2026-07-22";
  };
  dot-skills = {
    pname = "dot-skills";
    version = "f89a949c8911db02f7174fb4f6197e429a6b1402";
    src = fetchgit {
      url = "https://github.com/pproenca/dot-skills";
      rev = "f89a949c8911db02f7174fb4f6197e429a6b1402";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0p0lK45tJ2cdya04Dx1lLSfLt6o722P+eSzLFuRJsM0=";
    };
    date = "2026-07-23";
  };
  humanlayer-skills = {
    pname = "humanlayer-skills";
    version = "39fb32786ae7a7cd864cf2c237148c38b1e4db07";
    src = fetchgit {
      url = "https://github.com/humanlayer/skills";
      rev = "39fb32786ae7a7cd864cf2c237148c38b1e4db07";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-P7KBvZqdC4IoSL20CTNyAXRYpSbT4p15vbKI+yk/r/g=";
    };
    date = "2026-06-30";
  };
  itechmeat-skills = {
    pname = "itechmeat-skills";
    version = "19d1a742643ace2e875cda93353a59356f518f1d";
    src = fetchgit {
      url = "https://github.com/itechmeat/llm-code";
      rev = "19d1a742643ace2e875cda93353a59356f518f1d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MU/sQM1n1Lf7PjfcecEK2vi62pb3fH6+i4XUpNte6fA=";
    };
    date = "2026-07-18";
  };
  linear = {
    pname = "linear";
    version = "2.2.0";
    src = fetchurl {
      url = "https://github.com/schpet/linear-cli/releases/download/v2.2.0/linear-aarch64-apple-darwin.tar.xz";
      sha256 = "sha256-VkDDqAypDhQYAJrswtSQ7hNZ0tzW3w8ZogIqzktsAEc=";
    };
  };
  linear-cli-skills = {
    pname = "linear-cli-skills";
    version = "487d682f7bd3c2323e8151c082c457acf34fd108";
    src = fetchgit {
      url = "https://github.com/schpet/linear-cli";
      rev = "487d682f7bd3c2323e8151c082c457acf34fd108";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-UPO8OSnAPTaQ4iREdkVmL8H33OF3MWQyNXjzqPsa0Ek=";
    };
    date = "2026-07-22";
  };
  mattpocock-skills = {
    pname = "mattpocock-skills";
    version = "ed37663cc5fbef691ddfecd080dff42f7e7e350d";
    src = fetchgit {
      url = "https://github.com/mattpocock/skills";
      rev = "ed37663cc5fbef691ddfecd080dff42f7e7e350d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-o/H9s3t6ahBqFwpkOMBOTwpsvb33pgvpI9n0PA+uLYM=";
    };
    date = "2026-07-21";
  };
  mole = {
    pname = "mole";
    version = "1.47.1";
    src = fetchurl {
      url = "https://github.com/tw93/mole/archive/refs/tags/V1.47.1.tar.gz";
      sha256 = "sha256-X1yKAcZ7ZE57umWps51hRhqwVDot+p51W1TPrN8h+hA=";
    };
  };
  oh-my-openagent = {
    pname = "oh-my-openagent";
    version = "4.19.1";
    src = fetchurl {
      url = "https://github.com/code-yeongyu/oh-my-openagent/archive/refs/tags/v4.19.1.tar.gz";
      sha256 = "sha256-YB1hvGPwB52gCMUl4m885kJQm4MWTVARIR6uKRMgq3s=";
    };
  };
  omp = {
    pname = "omp";
    version = "17.0.8";
    src = fetchurl {
      url = "https://github.com/can1357/oh-my-pi/releases/download/v17.0.8/omp-darwin-arm64";
      sha256 = "sha256-ctgYEiMLhvyxcNJze+AXOOeppK/NH0gBkZS/cgNNyck=";
    };
  };
  orca-skills = {
    pname = "orca-skills";
    version = "7ab601487c2e4c05b7067a5157e395300a0bdc0c";
    src = fetchgit {
      url = "https://github.com/stablyai/orca";
      rev = "7ab601487c2e4c05b7067a5157e395300a0bdc0c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XP2tPtoMsb1nnzuKFB6cu+Gu/Gn0JrrPW66h/wEGP6M=";
    };
    date = "2026-07-23";
  };
  playwriter-skills = {
    pname = "playwriter-skills";
    version = "ea2fa9b32f1d779bcc27304f2d3f484fe6b63b0e";
    src = fetchgit {
      url = "https://github.com/remorses/playwriter";
      rev = "ea2fa9b32f1d779bcc27304f2d3f484fe6b63b0e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dn2HEwFgjKXs5iiSZD6UZ8YpdsPPVFNcWna2EO8INXk=";
    };
    date = "2026-07-17";
  };
  pup = {
    pname = "pup";
    version = "1.7.0";
    src = fetchurl {
      url = "https://github.com/datadog-labs/pup/releases/download/v1.7.0/pup_1.7.0_Darwin_arm64.tar.gz";
      sha256 = "sha256-nh1/sdzsYPvI/syLwUhb02QtmCNGSwaZRrczloFbNgU=";
    };
  };
  pup-skills = {
    pname = "pup-skills";
    version = "001239b5293a4081a5135e6e71167a45e0cc4320";
    src = fetchgit {
      url = "https://github.com/datadog-labs/pup";
      rev = "001239b5293a4081a5135e6e71167a45e0cc4320";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zXb6SM6ylFVoIg+M7loNvPT45mda1okTSXslfLzOHpQ=";
    };
    date = "2026-07-22";
  };
  vercel-skills-cli = {
    pname = "vercel-skills-cli";
    version = "e173b8c88f2581cfdaa1b6767c6519a08155790e";
    src = fetchgit {
      url = "https://github.com/vercel-labs/skills";
      rev = "e173b8c88f2581cfdaa1b6767c6519a08155790e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NkvFJW5Gg/5aCik6mO7VB1Gke5xESf3/uxw2c7tHOv4=";
    };
    date = "2026-07-22";
  };
  wacli = {
    pname = "wacli";
    version = "0.13.0";
    src = fetchurl {
      url = "https://github.com/openclaw/wacli/releases/download/v0.13.0/wacli_0.13.0_darwin_universal.tar.gz";
      sha256 = "sha256-hneMQTqMtCintroFqxvNL4s1RKujoOoe0Sxw5X2U+Xk=";
    };
  };
  worktrunk-skills = {
    pname = "worktrunk-skills";
    version = "a3de0b0db67e5204248c755d35489ef537f01f1c";
    src = fetchgit {
      url = "https://github.com/max-sixty/worktrunk";
      rev = "a3de0b0db67e5204248c755d35489ef537f01f1c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PYufLJbOofUdaLa6IDBzj8F5TSLzvZNnaozorqMcvxc=";
    };
    date = "2026-07-22";
  };
  wshobson-agents = {
    pname = "wshobson-agents";
    version = "c4b82b0ad771190355eb8e204b1329732a18449a";
    src = fetchgit {
      url = "https://github.com/wshobson/agents";
      rev = "c4b82b0ad771190355eb8e204b1329732a18449a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-/7pBdX0uJcKM0ihcSvcrP2Ae9aTK688GBhgaSNesXRU=";
    };
    date = "2026-07-18";
  };
  zed = {
    pname = "zed";
    version = "1.12.0";
    src = fetchurl {
      url = "https://github.com/zed-industries/zed/releases/download/v1.12.0/Zed-aarch64.dmg";
      sha256 = "sha256-B16s1iVGyqI/Hrbog3kQ2sJwS0Of+FwxuoqF/tBaEYw=";
    };
  };
}
