# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agent-browser-skills = {
    pname = "agent-browser-skills";
    version = "328ce8a98560ac7bac8fa81f53a718822550b94e";
    src = fetchgit {
      url = "https://github.com/vercel-labs/agent-browser";
      rev = "328ce8a98560ac7bac8fa81f53a718822550b94e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-MaN0yoOyRuNhv+e6//1QtEwH7C5dXGu2s+OdCowYf4I=";
    };
    date = "2026-06-05";
  };
  anthropic-skills = {
    pname = "anthropic-skills";
    version = "57546260929473d4e0d1c1bb75297be2fdfa1949";
    src = fetchgit {
      url = "https://github.com/anthropics/skills";
      rev = "57546260929473d4e0d1c1bb75297be2fdfa1949";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-1D9otXxDvmKASBu/vtAEWv6kE+U+jG4OxZpRLZbGEF0=";
    };
    date = "2026-06-09";
  };
  chrome-devtools-mcp-skills = {
    pname = "chrome-devtools-mcp-skills";
    version = "4f8eb7ad6beecc58f56ec383f9ff43549a5604d4";
    src = fetchgit {
      url = "https://github.com/ChromeDevTools/chrome-devtools-mcp";
      rev = "4f8eb7ad6beecc58f56ec383f9ff43549a5604d4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gQ5wRg721pvJ6xeze7DsIKrOjfW70GjFgBwfArx+HIE=";
    };
    date = "2026-06-09";
  };
  context7-skills = {
    pname = "context7-skills";
    version = "cc011a470743a38839a9fd54ff160a26d7680240";
    src = fetchgit {
      url = "https://github.com/upstash/context7";
      rev = "cc011a470743a38839a9fd54ff160a26d7680240";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2UFFrDcXcyUbTLu112Qm2pLYH6pGmbevYiv/X3GPn6c=";
    };
    date = "2026-06-09";
  };
  dot-skills = {
    pname = "dot-skills";
    version = "a86ba91476c0a3df3c7702f176c53023ea2ffe7c";
    src = fetchgit {
      url = "https://github.com/pproenca/dot-skills";
      rev = "a86ba91476c0a3df3c7702f176c53023ea2ffe7c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Aihfefulnrne5r1wYNwttAy2DtDW3EKcN1e47F7lSw4=";
    };
    date = "2026-05-31";
  };
  humanlayer-skills = {
    pname = "humanlayer-skills";
    version = "ecf602e2f9bb445831e36592af92c36bfad18960";
    src = fetchgit {
      url = "https://github.com/humanlayer/skills";
      rev = "ecf602e2f9bb445831e36592af92c36bfad18960";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xRlJS7kYEtAZ+pCphIVGbOyuRhwuW4JuJG1qDF9ns7o=";
    };
    date = "2026-03-17";
  };
  itechmeat-skills = {
    pname = "itechmeat-skills";
    version = "0ba69fd9bfdecae0dc0b555652cb9d3e3522eec2";
    src = fetchgit {
      url = "https://github.com/itechmeat/llm-code";
      rev = "0ba69fd9bfdecae0dc0b555652cb9d3e3522eec2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AeZxH2PXNOqzN8VLniC0sL6/kAJZrA5u90Uy+2XCEVQ=";
    };
    date = "2026-06-01";
  };
  linear = {
    pname = "linear";
    version = "2.0.0";
    src = fetchurl {
      url = "https://github.com/schpet/linear-cli/releases/download/v2.0.0/linear-aarch64-apple-darwin.tar.xz";
      sha256 = "sha256-Eh/h7ubZCyLnbk6Yy7YkR07s2XCkpMYi/U1QiJtX2sw=";
    };
  };
  linear-cli-skills = {
    pname = "linear-cli-skills";
    version = "fc85b919cdb62a668eecea6ea5484aad9da8f655";
    src = fetchgit {
      url = "https://github.com/schpet/linear-cli";
      rev = "fc85b919cdb62a668eecea6ea5484aad9da8f655";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-nmF834DXqLmHDKiAys8FARsXmRWyMKyUF7uDVpq5a8w=";
    };
    date = "2026-05-19";
  };
  oh-my-openagent = {
    pname = "oh-my-openagent";
    version = "4.8.1";
    src = fetchurl {
      url = "https://github.com/code-yeongyu/oh-my-openagent/archive/refs/tags/v4.8.1.tar.gz";
      sha256 = "sha256-7bL/aUA83AYUNCfF1ARcL0y7uKXypuwgth6FdsL/JJo=";
    };
  };
  orca-skills = {
    pname = "orca-skills";
    version = "ad66692e7c65b23461578b10f56d6ec5c08e410e";
    src = fetchgit {
      url = "https://github.com/stablyai/orca";
      rev = "ad66692e7c65b23461578b10f56d6ec5c08e410e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-34R3suyAzb1PCsbA5LbD/S4zGOWnW98bD1AGIsXoLYw=";
    };
    date = "2026-06-09";
  };
  playwriter-skills = {
    pname = "playwriter-skills";
    version = "9d837c0a8cfb573bc084edbd1d1b7d4e9654c965";
    src = fetchgit {
      url = "https://github.com/remorses/playwriter";
      rev = "9d837c0a8cfb573bc084edbd1d1b7d4e9654c965";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Edro54JOXIRho1be/1gaCBH5e6k1uu+Dia7CJoZL6CY=";
    };
    date = "2026-05-27";
  };
  pup = {
    pname = "pup";
    version = "1.0.0";
    src = fetchurl {
      url = "https://github.com/datadog-labs/pup/releases/download/v1.0.0/pup_1.0.0_Darwin_arm64.tar.gz";
      sha256 = "sha256-f5rIYm+ekn8bHkhsxs2AGqdp5fNte/R4G5j0K3d4uXw=";
    };
  };
  pup-skills = {
    pname = "pup-skills";
    version = "841588cdf7de4068e0aad8da2df8cad6849fd49f";
    src = fetchgit {
      url = "https://github.com/datadog-labs/pup";
      rev = "841588cdf7de4068e0aad8da2df8cad6849fd49f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dXVyUYHEREIQHdh6MQm8K0x3VNa8VQotuYLuqV8e+Kw=";
    };
    date = "2026-06-09";
  };
  vercel-skills-cli = {
    pname = "vercel-skills-cli";
    version = "a561e790756b2785b9ddb82285c4eb0a08258ac9";
    src = fetchgit {
      url = "https://github.com/vercel-labs/skills";
      rev = "a561e790756b2785b9ddb82285c4eb0a08258ac9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-y9AFt7xLzmaX3+6+N+97zg8QXJyt4G3m9ymrB6m/pmA=";
    };
    date = "2026-06-05";
  };
  wacli = {
    pname = "wacli";
    version = "0.11.0";
    src = fetchurl {
      url = "https://github.com/openclaw/wacli/releases/download/v0.11.0/wacli_0.11.0_darwin_universal.tar.gz";
      sha256 = "sha256-7dooiNYYE+bTqxdLd38WOCrwY5i9eKIIIu8i56FtKcU=";
    };
  };
  worktrunk-skills = {
    pname = "worktrunk-skills";
    version = "3f3c05bd4923cc84d583cfcf010b2fc776684b4e";
    src = fetchgit {
      url = "https://github.com/max-sixty/worktrunk";
      rev = "3f3c05bd4923cc84d583cfcf010b2fc776684b4e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fC4bEGYQ1OyontoyxfPJ5KoP4src3GihbvALu+aS3W0=";
    };
    date = "2026-06-09";
  };
  wshobson-agents = {
    pname = "wshobson-agents";
    version = "cf6059d030bf4fe96623ae2e596d2f31e35fedc0";
    src = fetchgit {
      url = "https://github.com/wshobson/agents";
      rev = "cf6059d030bf4fe96623ae2e596d2f31e35fedc0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QpfeAwDp9Oj3J9RZUaZPlrYsJvp2UxOwwU/JHWSUcas=";
    };
    date = "2026-06-05";
  };
}
