name: Check
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-devenv
      - name: Check flake
        run: nix flake check --no-build --no-warn-dirty
      - name: Run devenv tests
        run: devenv test
